### ISSUE TITLE
VRM Gruppe funktioniert nicht

### ISSUE THREAD

**Issue by CptCheesyCrust** [tobimori/paywallr#5]
Hi,

das entschlüsseln von Seiten der VRM Gruppe funktioniert leider nicht. Getestet in Firefox sowie Chrome. Unter Chrome auch nochmal separat mittels "Kann Webseiten lesen und ändern - wenn Addon angeklickt wird".

Chrome spuckt unter "Fehler" folgendes aus:

`const d = document;

const observer = new MutationObserver(function (mutations, me) {
  [...d.getElementsByTagName("meta")].map(n => n.getAttribute("property") == "laterpay:connector:config_token" && n.remove());
});

d.getElementsByTagName("meta")[1].getAttribute("name") == "isPremiumArticle" && 
d.getElementsByTagName("meta")[1].getAttribute("content") == "1" &&
observer.observe(d, {
  childList: true,
  subtree: true
});`

Wobei die Zeile 7
d.getElementsByTagName("meta")[1].getAttribute("name") == "isPremiumArticle" && 
gelb Hinterlegt ist.

Hoffe das hilft irgendwie weiter, sorry bin nur Enduser. ;-)

**Comment by tobimori** [comment]
Das Addon muss die Daten bereits beim Laden bearbeiten duerfen, weil die Ausfuehrung des Skripts irgendwie verhindert werden muss. Mit so einer oder einer aehnlichen Einstellung funktioniert das also nicht. In Chrome funktionierte VRM bei mir auch nicht, dass wird im naechsten Release gefixt sein. (siehe #3). In Firefox hatte ich den Bug nicht, ich lass das hier offen und schau mal was ich tun kann.

The addon must be allowed to edit the data at loading, because the execution of the script must be prevented somehow. With such a setting or a similar one this will not work. In Chrome VRM didn't work for me either, that will be fixed in the next release. (see #3). With Firefox I didn't had the bug, but I'll leave this open and see what I can do.

**Comment by tobimori** [comment]
Hi, habe gerade die neue Version veroeffentlicht. Absofort fuer Firefox und in ein paar Tagen dann auch im Chrome Store sein. LG.
